name: comment-tests

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  comment:
    name: Comment tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test
        continue-on-error: true

      - name: Capture test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jest-results
          path: |
            coverage/
            jest-results.json

      - name: Comment on PR with test results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const testResults = fs.readFileSync('jest-results.json', 'utf8');
            const pullRequestNumber = github.event.pull_request.number;
            const commentBody = `## Jest Test Results\n\`\`\`\n${testResults}\n\`\`\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequestNumber,
              body: commentBody
            });