name: comment-tests

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  comment:
    name: Comment tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests and capture output
        run: yarn test > "${{ github.workspace }}/test-results.txt" 2>&1 || true
        continue-on-error: true

      - name: Read test results
        id: test_results
        run: |
          TEST_RESULTS_PATH="${{ github.workspace }}/test-results.txt"
          if [ -s "$TEST_RESULTS_PATH" ]; then
            TEST_RESULTS=$(cat "$TEST_RESULTS_PATH")
            echo "::set-output name=data::$TEST_RESULTS"
          else
            echo "::set-output name=data::No test results were found."
          fi

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment_body = `Test results:\n\`\`\`\n${{ steps.test_results.outputs.data }}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_body
            })