name: comment-tests

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  comment:
    name: Comment tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const body = `Test results for: ${context.issue.number}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })