name: comment-tests

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main
      - develop

permissions: write-all

jobs:
  comment:
    name: Comment tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests and capture output
        run: yarn test > test-results.txt 2>&1 || echo "Tests failed"
        continue-on-error: true


      - name: Read test results
        id: test_results
        run: |
          if [ -s test-results.txt ]; then
            echo "::set-output name=data::$(<test-results.txt)"
          else
            echo "No test results were found."
            echo "::set-output name=data::No test results were found."
          fi

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment_body = `Test results:\n\`\`\`\n${{ steps.test_results.outputs.data }}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment_body
            })